
package net.etrs.ram.bad_cessonais.interop;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceClassementService", targetNamespace = "http://interop.mockup/", wsdlLocation = "http://201214-11:9090/ServeurFFbadWeb/ServiceClassement?wsdl")
public class ServiceClassementService
    extends Service
{

    private final static URL SERVICECLASSEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECLASSEMENTSERVICE_EXCEPTION;
    private final static QName SERVICECLASSEMENTSERVICE_QNAME = new QName("http://interop.mockup/", "ServiceClassementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://201214-11:9090/ServeurFFbadWeb/ServiceClassement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECLASSEMENTSERVICE_WSDL_LOCATION = url;
        SERVICECLASSEMENTSERVICE_EXCEPTION = e;
    }

    public ServiceClassementService() {
        super(__getWsdlLocation(), SERVICECLASSEMENTSERVICE_QNAME);
    }

    public ServiceClassementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECLASSEMENTSERVICE_QNAME, features);
    }

    public ServiceClassementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECLASSEMENTSERVICE_QNAME);
    }

    public ServiceClassementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECLASSEMENTSERVICE_QNAME, features);
    }

    public ServiceClassementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceClassementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceClassement
     */
    @WebEndpoint(name = "ServiceClassementPort")
    public ServiceClassement getServiceClassementPort() {
        return super.getPort(new QName("http://interop.mockup/", "ServiceClassementPort"), ServiceClassement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceClassement
     */
    @WebEndpoint(name = "ServiceClassementPort")
    public ServiceClassement getServiceClassementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interop.mockup/", "ServiceClassementPort"), ServiceClassement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECLASSEMENTSERVICE_EXCEPTION!= null) {
            throw SERVICECLASSEMENTSERVICE_EXCEPTION;
        }
        return SERVICECLASSEMENTSERVICE_WSDL_LOCATION;
    }

}
